python edit.py  --source_prompt "" \
                --target_prompt "a cartoon style Sir Charles Chaplin raising his left hand " \
                --guidance 2 \
                --source_img_dir 'examples/source/cartoon.jpg' \
                --num_steps 8 \
                --inject 1 \
                --name 'flux-dev' \
                --start_layer_index 0 \
                --end_layer_index 37 \
                --sampling_strategy 'diffusion_free_noise' \
                --output_prefix 'diffusion_free_noise' \
                --offload \
                --output_dir 'examples/edit-result/cartoon/' 